Document: pbnjson
Title: Debian pbnjson Manual
Author: <insert document author here>
Abstract: This manual describes what pbnjson is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pbnjson/pbnjson.sgml.gz

Format: postscript
Files: /usr/share/doc/pbnjson/pbnjson.ps.gz

Format: text
Files: /usr/share/doc/pbnjson/pbnjson.text.gz

Format: HTML
Index: /usr/share/doc/pbnjson/html/index.html
Files: /usr/share/doc/pbnjson/html/*.html
